<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class RegisterRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'name' => 'required|unique:users',
            'email' => 'required|unique:users|email',
            'password' => 'required|min:8|regex:/^(?=.*\d)(?=.*[A-Z]).*$/',
        ];
    }

    public function messages()
    {
        return [
            'name.required' => 'Bạn chưa nhập username.',
            'name.unique' => 'Username đã tồn tại. Vui lòng nhập username khác.',
            'email.required' => 'Bạn chưa nhập email.',
            'email.email' => 'Bạn chưa nhập đúng định dạng email.',
            'email.unique' => 'Email đã tồn tại. Vui lòng nhập email khác.',
            'password.required' => 'Bạn chưa nhập mật khẩu.',
            'password.min' => 'Mật khẩu phải có ít nhất 8 ký tự bao gồm chữ cái hoa, chữ số.',
            'password.regex' => 'Mật khẩu phải có ít nhất 8 ký tự bao gồm chữ cái hoa, chữ số.',
        ]; // TODO: Change the autogenerated stub
    }
}
